language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

before_install:
  - cd ../..
  - chmod +x build.sh
  - travis_retry composer self-update

install:
  - composer install
  
script:
  - ./build.sh
